/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forme;

import forme.kartonpacijenta.FrmKartonPacijenta;
import forme.usluga.FrmUsluga;
import java.awt.BorderLayout;
import javax.swing.JFrame;

/**
 *
 * @author User
 */
public class FrmGlavna extends javax.swing.JFrame {

    /**
     * Creates new form FrmGlavna
     */
    public FrmGlavna() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jPopupMenu1 = new javax.swing.JPopupMenu();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableKonfiguracija = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuKartoniPacijenata = new javax.swing.JMenu();
        JMenuItemNoviKarton = new javax.swing.JMenuItem();
        JMenuItemPrikazKartona = new javax.swing.JMenuItem();
        jMenuUsluge = new javax.swing.JMenu();
        jMenuItemPokreni = new javax.swing.JMenuItem();
        jMenuKonfiguracija = new javax.swing.JMenu();
        jMenuItemBaza = new javax.swing.JMenuItem();
        jMenuOAplikaciji = new javax.swing.JMenu();
        JMenuItemOAutoru = new javax.swing.JMenuItem();

        jMenu3.setText("File");
        jMenuBar2.add(jMenu3);

        jMenu4.setText("Edit");
        jMenuBar2.add(jMenu4);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTableKonfiguracija.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTableKonfiguracija);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(308, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(190, Short.MAX_VALUE))
        );

        jLayeredPane1.setLayer(jPanel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jMenuKartoniPacijenata.setText("KartoniPacijenata");
        jMenuKartoniPacijenata.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuKartoniPacijenataActionPerformed(evt);
            }
        });

        JMenuItemNoviKarton.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, 0));
        JMenuItemNoviKarton.setText(" Novi karton");
        JMenuItemNoviKarton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMenuItemNoviKartonActionPerformed(evt);
            }
        });
        jMenuKartoniPacijenata.add(JMenuItemNoviKarton);

        JMenuItemPrikazKartona.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, 0));
        JMenuItemPrikazKartona.setText("Prikaz svih kartona");
        JMenuItemPrikazKartona.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMenuItemPrikazKartonaActionPerformed(evt);
            }
        });
        jMenuKartoniPacijenata.add(JMenuItemPrikazKartona);

        jMenuBar1.add(jMenuKartoniPacijenata);

        jMenuUsluge.setText("Usluge");

        jMenuItemPokreni.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, 0));
        jMenuItemPokreni.setText("Pokreni");
        jMenuItemPokreni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemPokreniActionPerformed(evt);
            }
        });
        jMenuUsluge.add(jMenuItemPokreni);

        jMenuBar1.add(jMenuUsluge);

        jMenuKonfiguracija.setText("Konfiguracija");

        jMenuItemBaza.setText("Baza");
        jMenuItemBaza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemBazaActionPerformed(evt);
            }
        });
        jMenuKonfiguracija.add(jMenuItemBaza);

        jMenuBar1.add(jMenuKonfiguracija);

        jMenuOAplikaciji.setText("O aplikaciji");

        JMenuItemOAutoru.setText("O autoru");
        JMenuItemOAutoru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMenuItemOAutoruActionPerformed(evt);
            }
        });
        jMenuOAplikaciji.add(JMenuItemOAutoru);

        jMenuBar1.add(jMenuOAplikaciji);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JMenuItemOAutoruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMenuItemOAutoruActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JMenuItemOAutoruActionPerformed

    private void jMenuKartoniPacijenataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuKartoniPacijenataActionPerformed

    }//GEN-LAST:event_jMenuKartoniPacijenataActionPerformed

    private void JMenuItemNoviKartonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMenuItemNoviKartonActionPerformed
        FrmKartonPacijenta jfkartonpacijenta = new FrmKartonPacijenta(this, true);
        jfkartonpacijenta.getJtabpanelistakartona().setSelectedIndex(0);
        jfkartonpacijenta.setVisible(true);    }//GEN-LAST:event_JMenuItemNoviKartonActionPerformed

    private void JMenuItemPrikazKartonaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMenuItemPrikazKartonaActionPerformed
        FrmKartonPacijenta jdialoglistakartona = new FrmKartonPacijenta(this, true);
        jdialoglistakartona.getJtabpanelistakartona().setSelectedIndex(1);
        jdialoglistakartona.setLayout(new BorderLayout());
        //  jdialoglistakartona.add(new FrmPrikazKartonaPacijenataTabela(),BorderLayout.CENTER);
        pack();
        jdialoglistakartona.setVisible(true);
    }//GEN-LAST:event_JMenuItemPrikazKartonaActionPerformed

    private void jMenuItemPokreniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemPokreniActionPerformed
        JFrame frmu = new FrmUsluga();
        frmu.setVisible(true);
    }//GEN-LAST:event_jMenuItemPokreniActionPerformed

    private void jMenuItemBazaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemBazaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItemBazaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmGlavna.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmGlavna.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmGlavna.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmGlavna.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmGlavna().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem JMenuItemNoviKarton;
    private javax.swing.JMenuItem JMenuItemOAutoru;
    private javax.swing.JMenuItem JMenuItemPrikazKartona;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItemBaza;
    private javax.swing.JMenuItem jMenuItemPokreni;
    private javax.swing.JMenu jMenuKartoniPacijenata;
    private javax.swing.JMenu jMenuKonfiguracija;
    private javax.swing.JMenu jMenuOAplikaciji;
    private javax.swing.JMenu jMenuUsluge;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableKonfiguracija;
    // End of variables declaration//GEN-END:variables
}
