/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forme.kartonpacijenta;

import domen.KartonPacijenta;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTabbedPane;
import poslovnalogika.Kontroler;

/**
 *
 * @author User
 */
public class FrmKartonPacijenta extends javax.swing.JDialog {

    /**
     * Creates new form FrmKartonPacijenta
     */
    // private JTabbedPane jtabpanelistakartona;
    public FrmKartonPacijenta(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    public JTabbedPane getJtabpanelistakartona() {
        return jtabpanelistakartona;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDatePickerUtil1 = new org.jdatepicker.util.JDatePickerUtil();
        jDatePickerUtil2 = new org.jdatepicker.util.JDatePickerUtil();
        jDateComponentFactory1 = new org.jdatepicker.JDateComponentFactory();
        jDatePickerUtil3 = new org.jdatepicker.util.JDatePickerUtil();
        jDatePickerUtil4 = new org.jdatepicker.util.JDatePickerUtil();
        jDatePickerUtil5 = new org.jdatepicker.util.JDatePickerUtil();
        jPanel3 = new javax.swing.JPanel();
        utilDateModel1 = new org.jdatepicker.impl.UtilDateModel();
        jtabpanelistakartona = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jlbjmbg = new javax.swing.JLabel();
        jtfjmbg = new javax.swing.JTextField();
        jlblbo = new javax.swing.JLabel();
        jtflbo = new javax.swing.JTextField();
        jtfime = new javax.swing.JTextField();
        jlbime = new javax.swing.JLabel();
        jlbprezime = new javax.swing.JLabel();
        jtfprezime = new javax.swing.JTextField();
        jlbpol = new javax.swing.JLabel();
        jlbdatrodj = new javax.swing.JLabel();
        jlbadresa = new javax.swing.JLabel();
        jlbkontaktelefon = new javax.swing.JLabel();
        jtfadresa = new javax.swing.JTextField();
        jtfkontakttelefon = new javax.swing.JTextField();
        jcomboboxpol = new javax.swing.JComboBox<>();
        jbtnsacuvaj = new javax.swing.JToggleButton();
        jlbkrvnagrupa = new javax.swing.JLabel();
        jtfdatrodj = new javax.swing.JTextField();
        jcomboboxkrvnagrupa = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        frmPrikazKartonaPacijenataTabela2 = new forme.kartonpacijenta.FrmPrikazKartonaPacijenataTabela();

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 458, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 406, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jlbjmbg.setText("JMBG");

        jtfjmbg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfjmbgActionPerformed(evt);
            }
        });

        jlblbo.setText("LBO");

        jtflbo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtflboActionPerformed(evt);
            }
        });

        jtfime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfimeActionPerformed(evt);
            }
        });

        jlbime.setText("Ime");

        jlbprezime.setText("Prezime");

        jtfprezime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfprezimeActionPerformed(evt);
            }
        });

        jlbpol.setText("Pol");

        jlbdatrodj.setText("Datum rođenja");

        jlbadresa.setText("Adresa");

        jlbkontaktelefon.setText("Kontakt telefon");

        jtfadresa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfadresaActionPerformed(evt);
            }
        });

        jtfkontakttelefon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfkontakttelefonActionPerformed(evt);
            }
        });

        jcomboboxpol.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "muški", "ženski", " ", " ", " " }));
        jcomboboxpol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcomboboxpolActionPerformed(evt);
            }
        });

        jbtnsacuvaj.setText("Sačuvaj");
        jbtnsacuvaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnsacuvajActionPerformed(evt);
            }
        });

        jlbkrvnagrupa.setText("Krvna grupa");

        jtfdatrodj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfdatrodjActionPerformed(evt);
            }
        });

        jcomboboxkrvnagrupa.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "O", "A", "B", "AB" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jlblbo)
                                    .addComponent(jlbime)
                                    .addComponent(jlbprezime)
                                    .addComponent(jlbpol)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jlbkontaktelefon))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jlbjmbg))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jlbkrvnagrupa)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jtfjmbg, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                            .addComponent(jtfime, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                            .addComponent(jtflbo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                            .addComponent(jtfprezime, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                            .addComponent(jtfadresa, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                            .addComponent(jtfkontakttelefon, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                            .addComponent(jcomboboxpol, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jcomboboxkrvnagrupa, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addComponent(jbtnsacuvaj))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlbdatrodj, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jlbadresa))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jtfdatrodj, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(513, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlbjmbg)
                            .addComponent(jtfjmbg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtflbo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlblbo))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlbime)
                            .addComponent(jtfime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtfprezime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlbprezime))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jlbpol)
                            .addComponent(jcomboboxpol, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlbdatrodj)
                            .addComponent(jtfdatrodj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtfadresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlbadresa))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtfkontakttelefon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlbkontaktelefon))
                        .addGap(38, 38, 38))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jlbkrvnagrupa)
                        .addComponent(jcomboboxkrvnagrupa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbtnsacuvaj)
                .addGap(20, 20, 20))
        );

        jtabpanelistakartona.addTab("Osnovni podaci", jPanel1);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(frmPrikazKartonaPacijenataTabela2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(frmPrikazKartonaPacijenataTabela2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(111, Short.MAX_VALUE))
        );

        jtabpanelistakartona.addTab("Lista Kartona", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jtabpanelistakartona)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jtabpanelistakartona)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtfjmbgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfjmbgActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfjmbgActionPerformed

    private void jtflboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtflboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtflboActionPerformed

    private void jtfimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfimeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfimeActionPerformed

    private void jtfprezimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfprezimeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfprezimeActionPerformed

    private void jtfadresaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfadresaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfadresaActionPerformed

    private void jtfkontakttelefonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfkontakttelefonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfkontakttelefonActionPerformed

    private void jcomboboxpolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcomboboxpolActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcomboboxpolActionPerformed

    private void jbtnsacuvajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnsacuvajActionPerformed
//        try {
            String jmbg = jtfjmbg.getText().trim();
            String licnibrojosiguranika = (jtflbo.getText().trim());
            String ime = jtfime.getText().trim();
            String prezime = jtfprezime.getText().trim();
            String pol = (String) jcomboboxpol.getSelectedItem();
            String datumRođ = jtfdatrodj.getText().trim();
            String adresa = jtfadresa.getText().trim();
            String kontaktTelefon = jtfkontakttelefon.getText().trim();
            String krvnaGrupa = (String) jcomboboxkrvnagrupa.getSelectedItem();

            SimpleDateFormat sdf = new SimpleDateFormat("dd.MM.yyyy");
            Date datumRođenja = null;
            int lbo=Integer.parseInt(licnibrojosiguranika);
             
        try {
            datumRođenja = sdf.parse(datumRođ);
        } catch (ParseException ex) {
            Logger.getLogger(FrmKartonPacijenta.class.getName()).log(Level.SEVERE, null, ex);
        }
                
               
//uradi validaciju
            // karton = kreirajIIzvrsiValidaciju(jmbg, lbo, ime, prezime, pol, datumRođenja, adresa, kontaktTelefon, krvnaGrupa);
            //  Repozitorijum.sacuvajPoslovnogPartnera(partner);
            KartonPacijenta karton = new KartonPacijenta(jmbg, lbo, ime, prezime, pol, datumRođenja, adresa, kontaktTelefon, krvnaGrupa);
           // Kontroler.getInstance().sacuvajKartonPacijenta(karton);
//            JOptionPane.showMessageDialog(this, "Karton pacijenta uspešno sačuvan");
//        } catch (Exception ex) {
//            JOptionPane.showMessageDialog(this, "Karton pacijenta nije sačuvan. " + ex.getMessage());
//        }
        ;
        ;

    }//GEN-LAST:event_jbtnsacuvajActionPerformed

    private void jtfdatrodjActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfdatrodjActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfdatrodjActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmKartonPacijenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmKartonPacijenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmKartonPacijenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmKartonPacijenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FrmKartonPacijenta dialog = new FrmKartonPacijenta(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private forme.kartonpacijenta.FrmPrikazKartonaPacijenataTabela frmPrikazKartonaPacijenataTabela2;
    private org.jdatepicker.JDateComponentFactory jDateComponentFactory1;
    private org.jdatepicker.util.JDatePickerUtil jDatePickerUtil1;
    private org.jdatepicker.util.JDatePickerUtil jDatePickerUtil2;
    private org.jdatepicker.util.JDatePickerUtil jDatePickerUtil3;
    private org.jdatepicker.util.JDatePickerUtil jDatePickerUtil4;
    private org.jdatepicker.util.JDatePickerUtil jDatePickerUtil5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JToggleButton jbtnsacuvaj;
    private javax.swing.JComboBox<String> jcomboboxkrvnagrupa;
    private javax.swing.JComboBox<String> jcomboboxpol;
    private javax.swing.JLabel jlbadresa;
    private javax.swing.JLabel jlbdatrodj;
    private javax.swing.JLabel jlbime;
    private javax.swing.JLabel jlbjmbg;
    private javax.swing.JLabel jlbkontaktelefon;
    private javax.swing.JLabel jlbkrvnagrupa;
    private javax.swing.JLabel jlblbo;
    private javax.swing.JLabel jlbpol;
    private javax.swing.JLabel jlbprezime;
    private javax.swing.JTabbedPane jtabpanelistakartona;
    private javax.swing.JTextField jtfadresa;
    private javax.swing.JTextField jtfdatrodj;
    private javax.swing.JTextField jtfime;
    private javax.swing.JTextField jtfjmbg;
    private javax.swing.JTextField jtfkontakttelefon;
    private javax.swing.JTextField jtflbo;
    private javax.swing.JTextField jtfprezime;
    private org.jdatepicker.impl.UtilDateModel utilDateModel1;
    // End of variables declaration//GEN-END:variables

    private KartonPacijenta kreirajIIzvrsiValidaciju(String jmbg, int lbo, String ime, String prezime, String pol, Date datumRođenja, String adresa, String kontaktTelefon, String krvnaGrupa) throws Exception {
        if (jmbg == null || jmbg.isEmpty()) {
            throw new Exception("Morate uneti jmbg");
        }
        if (ime == null || ime.isEmpty()) {
            throw new Exception("Morate uneti ime");
        }
        if (prezime == null || prezime.isEmpty()) {
            throw new Exception("Morate uneti prezime");
        }
        return new KartonPacijenta(jmbg, lbo, ime, prezime, pol, datumRođenja, adresa, kontaktTelefon, krvnaGrupa);

    }

    public void setJtabpanelistakartona(JTabbedPane jtabpanelistakartona) {
        this.jtabpanelistakartona = jtabpanelistakartona;
    }
}
